version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        versions: ["*"]
        update-types: ["all"]
        directory: "/vuln_app"
    allow:
      - dependency-type: "direct"
        update-types: ["security"]
    versioning-strategy: "increase-if-necessary"
