version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    versioning-strategy: increase-if-necessary
    reviewers:
      - "PatrickTulskie"
      - "Shawanga"
    # Ignore dependencies in /vuln_app directory
  - package-ecosystem: "bundler"
    directory: "/vuln_app"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
